---
version: "3.9"
services:
  mysql:
    image: mariadb:10.6
    container_name: api_database
    environment:
      - MARIADB_USER=user
      - MARIADB_PASSWORD=mypassword
      - MARIADB_DATABASE=api_database
      - MARIADB_ROOT_PASSWORD=rootpassword
      - MARIADB_ROOT_HOST=%
    ports:
      - 3305:3306
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 801:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql

volumes:
  db:
